### ISSUE TITLE
Kill Limit

### ISSUE THREAD

**Issue by chrisinajar** [AngelArenaAllstars/aaa#1]
The way that you win! Lets call them points instead of kills, so that other things can count towards the points!

* [x] Create panorama element for voting for the kill limit
* [x] When kill limit is hit, win game and show some sort of blank win screen (probably a meme image)

**Comment by chrisinajar** [comment]
Voting element is completed, however the votes are not yet tallied.

Add up all the votes when that screen is dismissed, and store off the result as a number. 50 for short, 100 for normal, 200 for long.

Create a new global value for each team called "Points". Whenever either team gets a kill, add 1 to the points. When points > goal, win the game for that team.

**Note**: Once duels are completed, the winning team will need to win a duel before they actually win. This will be done as a separate unit of work at another time and tracked in another ticket.

**Comment by Sangoku** [comment]
What kind of meme :)  am thinking to join your little project as pet project... can you collor me intriged? Roadmap, storylines and other stuff. Want to be sure the project is on a possible track.

**Comment by Chronophylos** [comment]
Look at PR #78

**Comment by chrisinajar** [comment]
This should be completed, we can open other tickets for remaining tasks.

@Sangoku if you're serious about helping, get a local instance running and join the discord. We have miles and miles planned, and it's basically just Chrono and I implementing right now.
