### ISSUE TITLE
Translations for need/greed/pass UI

### ISSUE THREAD

**Issue by chrisinajar** [AngelArenaAllstars/aaa#14]
### Request for translations
Need/Greed/Pass UI, as shown here... https://clips.twitch.tv/chrisinajar/GiftedAlligatorAsianGlow

**Key**: "ngp_need"  
**English copy**: "Need"  
**Key**: "ngp_greed"  
**English copy**: "Greed"  
**Key**: "ngp_pass"  
**English copy**: "Pass"  
**Key**: "ngp_builds_into"  
**English copy**: "Builds into"  

Add in the complete translation before checking the list item.

 * [x] Chinese translation: 
   * [ ] **ngp_need**: "急需"
   * [ ] **ngp_greed**: "贪得"
   * [ ] **ngp_pass**: "弃权"
   * [ ] **ngp_builds_into**: "可组建成"
 * [x] Russian translation:
   * [ ] **ngp_need**: "Нужно"
   * [ ] **ngp_greed**: "Хочу!"
   * [ ] **ngp_pass**: "Пас"
   * [ ] **ngp_builds_into**: "Используется в"
 * [x] Spanish translation:
   * [ ] **ngp_need:** "Necesidad"
   * [ ] **ngp_greed:** "Codicia"
   * [ ] **ngp_pass:** "Pasar"
   * [ ] **ngp_builds_into:** "Se mejora a"
 * [x] Portuguese translation:
   * [ ] **ngp_need**: "Necessidade"
   * [ ] **ngp_greed**: "Ganância"
   * [ ] **ngp_pass**: "Passe"
   * [ ] **ngp_builds_into**: "Parte de"

**Comment by DJBotan** [comment]
Russian translation: 
 ngp_need: "Нужно"
 ngp_greed: "Хочу!"
 ngp_pass: "Пас"
 ngp_builds_into: "Используется в"

**Comment by DrWallaceBreen** [comment]
Spanish translation:
**ngp_need:** "Necesidad"
**ngp_greed:** "Codicia"
**ngp_pass:** "Pasar"
**ngp_builds_into:** "Se mejora a"

**Comment by dkHugh** [comment]
Chinese translation:
ngp_need: "急需"
ngp_greed: "贪得"
ngp_pass: "弃权"
ngp_builds_into: "可组建成"

**Comment by Haganeko** [comment]
Portuguese translation:
ngp_need: "Necessidade"
ngp_greed: "Ganância"
ngp_pass: "Passe"
ngp_builds_into: "Parte de"

**Comment by germanerd** [comment]
German translation:
ngp_need: "Bedarf"
ngp_greed: "Gier"
ngp_pass: "Passen"
ngp_builds_into: "Wird kombiniert zu"

**Comment by Murzer** [comment]
Edit to Russian translation:
 ngp_need: "Нужно"
 ngp_greed: "Хочу!"
 ngp_pass: "Пропустить"
 ngp_builds_into: "Собирается в"

**Comment by HarryPhoon** [comment]
Czech translation:
ngp_need: "Potřeba"
ngp_greed: "Chtíč"
ngp_pass: "Možná"
ngp_builds_into: "Staví se do"
