### ISSUE TITLE
Sand King Leveling bug

### ISSUE THREAD

**Issue by thepacman98** [AngelArenaAllstars/aaa#45]
Sang king cannot level anything at levels 1-4
Burrowstrike is available at 5, 10, 15 ......
Sandstorm and Caustic Finale can be leveled at 6, 11, 16.....
Epicenter can all be leveled at 6, 13, 20....
Once you hit the required level, all skill points necessary are given. Talents behave normally
No other hero that I have tested has this skill leveling pattern.

**Comment by KarmaticNeutral** [comment]
This is not a glitch for solely Sand King, it applies to all heroes.

Character Level requirements:

Abba
Q (+5) 1  6  11 16 21 26 31
W (+7) 1  8  15 22 29 36 43
E (+5) 1  6  11 16 21 26 31
R (+7) 6  13 20 27 34 41 48

Alch
Q (+5) 7  12 17 22 27 32 37
W (+5) 1  6  11 16 21 26 31
E (+5) 1  6  11 16 21 26 31
R (+7) 6  13 20 27 34 41 48

TA
Q (+5) 6  11 16 21 26 31 36
W (+7) 1  8  15 22 29 36 43
E (+5) 1  6  11 16 21 26 31
R (+5) 6  11 16 21 26 31 36

**Comment by chrisinajar** [comment]
These numbers are placeholders until we get the whole epic skill thing working.
