### ISSUE TITLE
That's a pitty problem

### ISSUE THREAD

**Issue by Krzysioka** [AngelArenaAllstars/aaa#48]
So i dont know how to tell u my idea, on twitch or on yt? i dont belive that u read all that shit. So read here. I was thinking about, that for example boots which are giving movement speed and attack, those decrease armor.  Anywas debuffs on items. It would make people to think which items to buy and it ll kill all cancer builds. ^_^ hope u like it

**Comment by chrisinajar** [comment]
I am not reading this idea.

From the readme:  
**Do not create or comment on tickets in this repository for game suggestions.**
