### ISSUE TITLE
Add gold values to creeps

### ISSUE THREAD

**Issue by chrisinajar** [AngelArenaAllstars/aaa#79]
Currently the values for gold per creep type are completely arbitrary. Replace them with this.

easy creep 15 gold initially
med creep 23 gold initially
hard creep 45 gold initially

multiplier at minute n is just n/2+1

**Comment by Haganeko** [comment]
Just to add, this represents a contribution of each camp to a team's total gold:
8% for an easy camp
14% for a medium camp
18% for a hard camp
With 4/4/3 creeps per spawn in easy/medium/hard camps

**Comment by Honeth** [comment]
Isn't this issue resolved?

**Comment by chrisinajar** [comment]
yup
